PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE hosts(
id INTEGER PRIMARY KEY,
nome VARCHAR(15),
sala VARCHAR(15)
);
CREATE TABLE tarefas(
id INTEGER PRIMARY KEY,
script VARCHAR(15),
host INTEGER,
FOREIGN KEY(host) REFERENCES hosts(id)
);
COMMIT;
